### ISSUE TITLE
Interface with stars

### ISSUE THREAD

**Issue by edzer** [USGS-R/ncdfgeom#65]
It would be good to interface this package with [`stars`](https://github.com/r-spatial/stars), as it has wider support for raster data cubes and their integration with vector data cubes done here, and links to the GDAL world.

**Comment by dblodgett-usgs** [comment]
I'm planning on digging into this starting in early August among a couple other coding projects. 

Related... see https://github.com/OSGeo/gdal/issues/1287 -- wchen329 is working for me to add a NetCDF-Geom implementation to OGR. That means it would be available to `sf` too right?

From my perspective, the thing from `ncdfgeom` that is most useful is the timeseries reading/writing functionality, right?
