### ISSUE TITLE
create.nc gives warning with current RNetCDF pkg

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/ncdfgeom#74]
```r
Warning message:
In create.nc(nc_file, large = TRUE) :
  Argument 'large' is deprecated; please specify 'format' instead
```
From within `write_timeseries_dsg`

I think this requires an arg update to deal with changes in `ncdf4` pkg

**Comment by jread-usgs** [comment]
I see this is `RNetCDF` not `ncdf4`. I'm also not seeing where this arg is used, so perhaps it is an odd warning from the RNetCDF pkg out of the control of this pkg. 

Will see if I can share a reproducible example to diagnose.

**Comment by dblodgett-usgs** [comment]
Odd -- I'm using the format argument in source. I wonder if things are out of date on CRAN?

**Comment by jread-usgs** [comment]
Looks like the source is up to date but CRAN is not, which is why I am getting this warning. 

CRAN source:
```r
nc <- create.nc(nc_file, large = TRUE)
```
github source:
```r
nc <- create.nc(nc_file, format = "offset64")
```

**Comment by dblodgett-usgs** [comment]
Alright -- I'll work on a CRAN update.

**Comment by dblodgett-usgs** [comment]
CRAN release is up. See https://cran.r-project.org/package=ncdfgeom
