### ISSUE TITLE
@param `instance_names` , if \code{numeric}, triggers `var.put.nc()` error

### ISSUE THREAD

**Issue by hcorson-dosch** [USGS-R/ncdfgeom#83]
While testing [an implementation of `write_timeseries_dsg`](https://github.com/hcorson-dosch/lake-temperature-model-prep/blob/gcm_driver_data_munge_pipeline/7_drivers_munge/src/GCM_driver_nc_utils.R#L105-L121), I initially provided a numeric vector of grid cell ids as the `instance_names` parameter, since the [documentation notes that the `instance_names` vector can be \code{character} or \code{numeric}](https://github.com/USGS-R/ncdfgeom/blob/master/R/write_timeseries_dsg.R#L4-L5). However, this triggered the following error upon execution:
```R
Error in var.put.nc(nc, pkg.env$dsg_timeseries_id, instance_names) : 
  length(count) == ndims is not TRUE
```
That pointed me to [this line](https://github.com/USGS-R/ncdfgeom/blob/master/R/write_timeseries_dsg.R#L210), so I dug into the addition of the `dsg_timeseries_id` variable. When [it is added](https://github.com/USGS-R/ncdfgeom/blob/master/R/write_timeseries_dsg.R#L150-L153), its type is set as "NC_CHAR", which triggers [this code block in `add_var()`](https://github.com/USGS-R/ncdfgeom/blob/9a1c8ee321ca5888c7a1c87e1008925f8162e157/R/0_ncdfgeom.R#L52-L59). That block determines the maximum length of the elements in the data vector (the `instance_names` vector), which is then used to define a new dimension (`char_dim`). Then, when the `dsg_timeseries_id` variable is defined with a call to `var.def.nc`, it is [defined as having  2 dimensions](https://github.com/USGS-R/ncdfgeom/blob/9a1c8ee321ca5888c7a1c87e1008925f8162e157/R/0_ncdfgeom.R#L59-L61) (`char_dim` and the original `dim` specified in the call to `add_var()` by the user, which is the already defined [`instance_dim_name` dimension](https://github.com/USGS-R/ncdfgeom/blob/master/R/write_timeseries_dsg.R#L146)). Two dimensions are defined in preparation for later adding the data to that type = "NC_CHAR" variable, because when character variables are added with `var.put.nc`, they have [an implied second dimension](https://rdrr.io/cran/RNetCDF/man/var.put.nc.html):
> When writing to NC_CHAR variables, character variables have an implied dimension corresponding to the string length. This implied dimension must be defined explicitly as the fastest-varying dimension of the NC_CHAR variable

Up to this point, providing a \code{numeric} vector as the `instance_names` vector doesn't trigger any errors. But when that data vector is later [added](https://github.com/USGS-R/ncdfgeom/blob/master/R/write_timeseries_dsg.R#L210) to the `dsg_timeseries_id` variable with `var.put.nc`, I'm guessing it prompts the `length(count) == ndims is not TRUE` error because numeric data do not have a second implied dimension when writing to a NetCDF variable.

If I change my `instance_names` vector to \code{character}, the call to `write_timeseries_dsg()` executes without errors and returns the expected NetCDF file.

**Comment by dblodgett-usgs** [comment]
Thanks for the report. This was an awkward point of the implementation -- at one point, I assumed that the timeseries ids had to be character -- that was the wrong assumption. 

Regardless, I just pushed up a commit in #82 that should fix this. Once the tests pass, we'll merge it and you should be good to go.
